### ISSUE TITLE
request_data command documentation

### ISSUE THREAD

**Issue by henne49** [dannerph/keba-kecontact#3]
Hi,

thank you for writing the keba python implementation for home-assistant. I have called the command, but I cannot see any result in home assistant, can you help me, how to use it, to get data off my keba? I have just installed the keba, but not yet charged. But reading documentation, at least report 100 should show up with all zeros.

xthx

**Comment by dannerph** [comment]
This repository is only for the python library that is used for the home assistant integration. For usage issues, please use the forum at home assistant: https://community.home-assistant.io/t/evse-keba-p30-integration/
