### ISSUE TITLE
BMW Wallbox Plus not recognized

### ISSUE THREAD

**Issue by infviza** [dannerph/keba-kecontact#8]
My BMW Wallbox Plus Product-ID starts with the following string: "BMW-10-ESS40022-E1R", whereas current current implementation is checking for "BMW-10-EC240522-E1R". Would it be possible to extend recognition to include model of my Wallbox Plus, too?

**Comment by dannerph** [comment]
Added your wallbox plus product ID. For the Keba charging stations, there is a structure, that is somehow understandable, for the BMW branded ones, I have no idea, which one is a plus and which one is a connected model :D
