### ISSUE TITLE
Support for "E total" with Keba P20

### ISSUE THREAD

**Issue by mschlappa** [dannerph/keba-kecontact#9]
Hi,

i am using a Keba P20 which identifies as "KC-P20-EC240130-000".

It seems that the  "Total Energy" value is not supported in this library (although the wallbox supports this feature) i think because of this line of code:

https://github.com/dannerph/keba-kecontact/blob/ba5e3d712f92a9b13701ec732114ccc487f7e374/keba_kecontact/chargingstation.py#L82

Can you add support the metering feature for this Keba Wallbox?

**Comment by mschlappa** [comment]
I created a Pull-Request to support my specific wallbox revision  : https://github.com/dannerph/keba-kecontact/pull/10

Marcus

**Comment by mschlappa** [comment]
I tested it successfully locally!

`
2024-11-09 13:41:02.469 DEBUG (MainThread) [keba_kecontact.connection] Send report 3 to 192.168.40.16
2024-11-09 13:41:03.247 DEBUG (MainThread) [keba_kecontact.connection] Datagram received from 192.168.40.16: {
"ID": "3",
"U1": 0,
"U2": 0,
"U3": 0,
"I1": 0,
"I2": 0,
"I3": 0,
"P": 0,
"PF": 0,
"E pres": 115997,
"E total": 245921613,
"Serial": "16314582",
"Sec": 889991
}
`

![image](https://github.com/user-attachments/assets/d33a7e40-dd0e-43c0-a33f-1d930c600484)

**Comment by dannerph** [comment]
fixed following a more generic approach using the product overview from here:
https://media.expleo.hu/documents/katalogusok/keba/kecontact_smart-charging-solutions_en_interactive.pdf
